### PR TITLE
Solves installation issue in MacOS

### PR DESCRIPTION
**Pull request by DaniMori**
`utils::choose.files()` gives issues when installing in MacOS, as apparently this function does not exist.

Given that the `utils` package comes with the standard R distribution, it is not necessary to import it in the NAMESPACE dependencies.

### CODE REVIEW

**Comment by DaniMori** [comment]
@Leafrancia please run the following on your MacOS:

```r
install_github("CCOMS-UAM/ecs-data", ref = "bugfix/mac-install")

ecs.data::config_ecs_folders()
```

If it works, approve the PR. Otherwise tell me about the errors please.

**Comment by Leafrancia** [comment]
It works but when I knitt a documento I have this error: 
´Error in running command C:/Program Files (x86)/Stata15/StataSE-64.´

**Comment by DaniMori** [comment]
Yes that's it, if you don't have Stata (or it is in a different path) it won't work.
Anyway the (previous) installation problem is solved?

**Comment by Leafrancia** [comment]
> Yes that's it, if you don't have Stata (or it is in a different path) it won't work.
> Anyway the (previous) installation problem is solved?

Yes! I have download stata but I think I have to change the path

**Review by Leafrancia — APPROVED** [review]

**Pull request merged**
